server:
  port: 7000

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    discovery:
      enabled: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  codec:
      max-in-memory-size: 2MB
  application:
    name: shenyu-gateway

shenyu:
  sync:
    nacos:
      url: ${spring.cloud.nacos.server-addr}
      # url: 配置成你的 nacos地址，集群环境请使用（,）分隔。
      namespace: sync-data
